/**
 * Curated seed catalog.
 *
 * Sources (see README "致谢 / Credits"):
 *  - https://github.com/awesome-dsh-plugin/awesome-dsh-plugin (community index)
 *  - https://github.com/omdsh-dev (DSH plugin community org, migrated from dsh-external)
 *  - https://github.com/deepseek-ai/deepseek-harness (official)
 *
 * Descriptions are quoted or lightly adapted from each project's README /
 * the awesome list; `descriptionZh` are original Chinese translations written
 * for this panel. Entries are data only — no code is copied from any project.
 */

import type { CatalogEntry } from './types.ts';

/** pnpm-friendly install spec from a GitHub repo URL. */
function gitSpec(repo: string): string {
  return repo.replace(/^https:\/\/github\.com\//, 'github:');
}

function entry(input: Omit<CatalogEntry, 'id'> & { id?: string }): CatalogEntry {
  const repo = input.repo;
  const id = input.id ?? (repo ? repo.replace(/^https:\/\/github\.com\//, '').split('#')[0] : input.title.toLowerCase().replace(/\s+/g, '-'));
  const install = input.install ?? (input.npm ?? (repo ? gitSpec(repo.split('#')[0]) : undefined));
  // A topic/repository URL is only a discovery hint.  It is not proof that
  // the repository root is a package that `dsh plugin add` can install.
  const installVerified = input.installVerified ?? Boolean(input.install || input.npm);
  return { ...input, id, install, installVerified, ...(installVerified ? { installSource: input.installSource ?? 'bundled' } : {}) };
}

export const SEED_ENTRIES: CatalogEntry[] = [
  entry({
    title: 'dsh-memory-evolve',
    titleZh: '长期记忆与自我进化',
    repo: 'https://github.com/csyangwen/dsh-memory-evolve',
    category: 'plugin',
    description: 'Cross-session long-term memory and background self-evolution for DeepSeek Harness.',
    descriptionZh: '为 DeepSeek Harness 提供跨会话长期记忆、待办与后台自我进化能力。',
    tags: ['memory', 'evolve', 'cordis', '记忆', '自我进化'],
    author: 'csyangwen',
    install: 'github:csyangwen/dsh-memory-evolve',
    installVerified: true,
    installSource: 'author',
  }),
  // ── 插件 · 模型与提供方 ───────────────────────────────────────────────
  entry({
    title: 'dsh-llm-fallbacks',
    titleZh: 'LLM 回退策略',
    repo: 'https://github.com/btspoony/dsh-llm-fallbacks',
    category: 'plugin',
    description: 'Role-based LLM retry & fallback strategies.',
    descriptionZh: '基于角色的 LLM 重试与回退策略，提升多模型路由的稳定性。',
    tags: ['llm', 'fallback', 'retry', '模型', '回退', '路由'],
    author: 'btspoony',
  }),
  entry({
    title: 'dsh-advisor',
    titleZh: '副模型顾问',
    repo: 'https://github.com/omdsh-dev/dsh-advisor',
    category: 'plugin',
    description: 'Pair a second model that passively reviews each turn and injects notes.',
    descriptionZh: '搭配一个会在每轮对话被动注入见解和审查的副模型。',
    tags: ['advisor', 'review', 'second-model', '顾问', '审查', '副模型'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'llm-adaptive',
    titleZh: '自适应模型路由',
    repo: 'https://github.com/dylan121322/llm-adaptive',
    category: 'plugin',
    description: 'Adaptive model routing: per-request complexity classification with automatic provider routing.',
    descriptionZh: '自适应模型路由：按请求复杂度自动分类并选择提供方。',
    tags: ['llm', 'routing', 'adaptive', '模型', '路由', '自适应'],
    author: 'dylan121322',
  }),
  entry({
    title: 'dsh-codex-connect',
    titleZh: 'Codex 接入',
    repo: 'https://github.com/franksong2702/dsh-codex-connect',
    category: 'plugin',
    description: 'Connect ChatGPT OAuth and OpenAI Codex models to DeepSeek Harness, with opt-in search and image tools.',
    descriptionZh: '将 ChatGPT OAuth 与 OpenAI Codex 模型接入 DSH，可选用搜索与图像工具。',
    tags: ['codex', 'openai', 'oauth', '接入', '模型'],
    author: 'franksong2702',
  }),
  entry({
    title: 'deepseek-harness-wallet',
    titleZh: '多提供方余额钱包',
    repo: 'https://github.com/feibi-mochi/deepseek-harness-wallet',
    category: 'plugin',
    description: 'Multi-provider wallet chip: official DeepSeek balance, per-session cost & tokens, recharge shortcut, low-balance alerts.',
    descriptionZh: '多提供方钱包组件：官方 DeepSeek 余额、会话成本与 token、充值入口与低余额提醒。',
    tags: ['balance', 'cost', 'wallet', '余额', '成本', '钱包'],
    author: 'feibi-mochi',
  }),

  // ── 插件 · 会话与消息 ─────────────────────────────────────────────────
  entry({
    title: 'dsh-incognito',
    titleZh: '隐身会话',
    repo: 'https://github.com/HuiHuitie-zhu/dsh-incognito',
    category: 'plugin',
    description: 'Incognito sessions: standalone ephemeral sub-agent, draggable floating window, zero traces on close.',
    descriptionZh: '隐身会话：独立的一次性子代理，可拖拽悬浮窗，关闭后不留痕迹。',
    tags: ['incognito', 'ephemeral', 'privacy', '隐身', '临时', '隐私'],
    author: 'HuiHuitie-zhu',
  }),
  entry({
    title: 'dsh-queue-plus',
    titleZh: '队列增强',
    repo: 'https://github.com/starslittle/dsh-queue-plus',
    category: 'plugin',
    description: 'Stock queue plus edit, remove, steer, reorder, clear-all, and 10-second undo.',
    descriptionZh: '队列增强：编辑、移除、转向、重排、清空与 10 秒撤销。',
    tags: ['queue', 'undo', '队列', '撤销'],
    author: 'starslittle',
  }),
  entry({
    title: 'dsh-bookmarks',
    titleZh: '书签收藏',
    repo: 'https://github.com/penguin-oo/dsh-bookmarks',
    category: 'plugin',
    description: 'Bookmark assistant replies with notes and tags; browse every bookmark in one center and export to Markdown.',
    descriptionZh: '为助手回复添加书签（备注 + 标签），集中浏览并导出 Markdown。',
    tags: ['bookmark', 'notes', 'export', '书签', '收藏', '导出'],
    author: 'penguin-oo',
  }),
  entry({
    title: 'dsh-solo-thinking',
    titleZh: '分支头脑风暴',
    repo: 'https://github.com/fredalxin/dsh-solo-thinking',
    category: 'plugin',
    description: 'Visual branch brainstorming that creates an isolated Session for each direction with a full tree tab.',
    descriptionZh: '可视化分支头脑风暴：每个方向创建独立会话，并提供完整树形视图。',
    tags: ['thinking', 'branch', 'brainstorm', '头脑风暴', '分支'],
    author: 'fredalxin',
  }),
  entry({
    title: 'dsh-webchatlike',
    titleZh: '网页聊天体验',
    repo: 'https://github.com/cindyguyuehu123/dsh-webchatlike',
    category: 'plugin',
    description: 'Bring the deepseek.com web/app chat experience to DSH: edit prompts and regenerate answers in place.',
    descriptionZh: '把 deepseek.com 的网页/App 聊天体验带入 DSH：原地编辑提示词并重新生成回答。',
    tags: ['chat', 'regenerate', 'edit', '聊天', '重生成', '编辑'],
    author: 'cindyguyuehu123',
  }),

  // ── 插件 · 记忆 ───────────────────────────────────────────────────────
  entry({
    title: 'dsh-mnemon',
    titleZh: '跨代理持久记忆',
    repo: 'https://github.com/omdsh-dev/dsh-mnemon',
    category: 'plugin',
    description: 'Cross-agent, local-first persistent memory: long-term memory sharing, semantic recall, knowledge graph, Sidebar UI.',
    descriptionZh: '跨代理、本地优先的持久记忆：长期记忆共享、语义召回、知识图谱与侧边栏 UI。',
    tags: ['memory', 'persistent', 'knowledge', '记忆', '持久化', '知识图谱'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-mneme',
    titleZh: '跨会话记忆',
    repo: 'https://github.com/modusensus/dsh-mneme/tree/main/dsh-mneme',
    category: 'plugin',
    description: 'Cross-session memory: SQLite + human-editable Markdown mirror, autoDream consolidation, fully-offline semantic search.',
    descriptionZh: '跨会话记忆：SQLite + 可人工编辑的 Markdown 镜像、自动整合、全离线语义搜索。',
    tags: ['memory', 'sqlite', 'semantic', '记忆', '语义搜索'],
    author: 'modusensus',
  }),
  entry({
    title: 'distill',
    titleZh: '对话蒸馏',
    repo: 'https://github.com/LoserFox/distill',
    category: 'plugin',
    description: 'Automatic conversation distillation: background subagent reflection + skill create/update.',
    descriptionZh: '自动对话蒸馏：后台子代理反思 + 自动创建/更新技能。',
    tags: ['distill', 'reflection', 'skill', '蒸馏', '反思'],
    author: 'LoserFox',
  }),
  entry({
    title: 'dsh-memory',
    titleZh: '带引用的记忆',
    repo: 'https://github.com/Jesse-njx/dsh-memory',
    category: 'plugin',
    description: 'Cited memory over DSH\'s lossless session log: distilled facts carry (sessionId, eventRange) citations.',
    descriptionZh: '基于无损会话日志的记忆：抽取的事实带 (会话, 事件区间) 引用，可回溯原文。',
    tags: ['memory', 'citation', 'session', '记忆', '引用'],
    author: 'Jesse-njx',
  }),

  // ── 插件 · 工具与能力 ─────────────────────────────────────────────────
  entry({
    title: 'dsh-toolkit',
    titleZh: '确定性工具集',
    repo: 'https://github.com/omdsh-dev/dsh-toolkit',
    category: 'plugin',
    description: 'DSH zero-dependency toolkit collection — ten deterministic tools: time / encoding / json / calculator / csv / regex / markdown / diff / stat / schema.',
    descriptionZh: 'DSH 零依赖工具包合集——time / encoding / json / calculator / csv / regex / markdown / diff / stat / schema 十个确定性工具，统一入口一键安装。',
    tags: ['tools', 'toolkit', 'collection', '工具', '工具集'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-genui',
    titleZh: 'GenUI 内联组件',
    repo: 'https://github.com/omdsh-dev/dsh-genui',
    category: 'plugin',
    description: 'Interactive UI components rendered inline in assistant replies via the dsh-ui fence: layout, charts, plots, forms, quizzes, mermaid, 3D scenes.',
    descriptionZh: '通过 dsh-ui 围栏在助手回复中内联渲染交互组件：布局、图表、表单、测验、mermaid、3D 场景等。',
    tags: ['ui', 'charts', 'mermaid', '组件', '图表', '渲染'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-inspect',
    titleZh: '运行时检查',
    repo: 'https://github.com/omdsh-dev/dsh-inspect',
    category: 'plugin',
    description: 'Inspect the running DSH runtime: services, events, slots and plugins through read-only providers.',
    descriptionZh: '检查运行中的 DSH 运行时：通过只读 provider 查看服务、事件、槽位与插件。',
    tags: ['inspect', 'diagnostics', 'runtime', '检查', '诊断'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-deep-research',
    titleZh: '深度研究',
    repo: 'https://github.com/omdsh-dev/dsh-deep-research',
    category: 'plugin',
    description: 'Deep research workflow for DSH: multi-agent evidence gathering and report synthesis.',
    descriptionZh: 'DSH 深度研究工作流：多代理证据收集与报告综合。',
    tags: ['research', 'agents', 'report', '研究', '报告'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-mcp-bridge',
    titleZh: 'MCP 服务器包',
    repo: 'https://github.com/Edge-Echo/dsh-mcp-bridge',
    category: 'plugin',
    description: 'Curated MCP server bundle: demo, memory, filesystem, GitHub, Playwright and remote HTTP MCP servers, plus a connectivity verifier tool.',
    descriptionZh: '精选 MCP 服务器包：demo、memory、filesystem、GitHub、Playwright 与远程 HTTP MCP，附连通性验证工具。',
    tags: ['mcp', 'bridge', 'servers', 'MCP', '桥接'],
    author: 'Edge-Echo',
  }),
  entry({
    title: 'Gemini-Eyes',
    titleZh: 'Gemini 视觉桥',
    repo: 'https://github.com/ConsoleSun/Gemini-Eyes',
    category: 'plugin',
    description: 'MCP bridge to gemini.google.com: vision analysis of images and videos, Imagen image and Veo video generation, no API key.',
    descriptionZh: '桥接 gemini.google.com 的 MCP：图像/视频视觉分析、Imagen 图像与 Veo 视频生成，无需 API Key。',
    tags: ['gemini', 'vision', 'mcp', '视觉', '图像'],
    author: 'ConsoleSun',
  }),
  entry({
    title: 'godot-bridge',
    titleZh: 'Godot 引擎桥',
    repo: 'https://github.com/Smalldy/godot-bridge',
    category: 'plugin',
    description: 'DSH↔Godot engine runtime bridge: launch and drive a Godot 4.x game through its in-game TCP server — 8 tools.',
    descriptionZh: 'DSH↔Godot 引擎运行时桥：通过游戏内 TCP 服务器启动并驱动 Godot 4.x 游戏，共 8 个工具。',
    tags: ['godot', 'game', 'bridge', '游戏', '引擎'],
    author: 'Smalldy',
  }),

  // ── 插件 · 工作流与自动化 ─────────────────────────────────────────────
  entry({
    title: 'dsh_captain',
    titleZh: 'GPT 计划 + 深度求索执行',
    repo: 'https://github.com/KanoNoUta/dsh-captain',
    category: 'plugin',
    description: 'GPT plans dependency DAGs, DeepSeek workers execute tasks with adaptive parallelism, optional GPT reviewer audits diffs.',
    descriptionZh: 'GPT 规划依赖 DAG，DeepSeek 工作线程自适应并行执行，可选 GPT 评审审计 diff 并驱动修复。',
    tags: ['workflow', 'orchestration', 'review', '工作流', '编排', '评审'],
    author: 'KanoNoUta',
  }),
  entry({
    title: 'dsh-routines',
    titleZh: '定时任务',
    repo: 'https://github.com/Jesse-njx/dsh-routines',
    category: 'plugin',
    description: 'Scheduled agents on a cron: run a prompt on a schedule and get the digest where you already are.',
    descriptionZh: 'Cron 定时代理：按计划运行提示词并把摘要送到你所在的界面。',
    tags: ['schedule', 'cron', 'automation', '定时', '自动化'],
    author: 'Jesse-njx',
  }),
  entry({
    title: 'dsh-automation',
    titleZh: '定时编码运行',
    repo: 'https://github.com/titanwings/dsh-automation',
    category: 'plugin',
    description: 'Scheduled coding runs in fresh agent sessions with auditable history.',
    descriptionZh: '在新代理会话中定时执行编码任务，历史可审计。',
    tags: ['schedule', 'coding', 'audit', '定时', '编码'],
    author: 'titanwings',
  }),
  entry({
    title: 'dsh-task-planner',
    titleZh: '任务规划器',
    repo: 'https://github.com/ztl34245881-commits/dsh-task-planner',
    category: 'plugin',
    description: 'Task planning with experience muscle-memory: condition-reflex recall of past solutions, LLM capability matching.',
    descriptionZh: '带经验肌肉记忆的任务规划：条件反射式回忆历史方案，并按 LLM 能力匹配。',
    tags: ['planning', 'experience', 'planner', '规划'],
    author: 'ztl34245881-commits',
  }),
  entry({
    title: 'dsh_workflow',
    titleZh: '多代理工作流',
    repo: 'https://github.com/icetomoyo/dsh_workflow',
    category: 'plugin',
    description: 'UltraCode-style multi-agent orchestration: a generatable, savable, governable, observable, resumable workflow layer.',
    descriptionZh: 'UltraCode 风格多代理编排：可生成、可保存、可治理、可观测、可恢复的工作流层。',
    tags: ['workflow', 'agents', 'orchestration', '工作流', '多代理'],
    author: 'icetomoyo',
  }),

  // ── 插件 · 通知与集成 ─────────────────────────────────────────────────
  entry({
    title: 'dsh-notification',
    titleZh: '桌面通知',
    repo: 'https://github.com/omdsh-dev/dsh-notification',
    category: 'plugin',
    description: 'Desktop notifications for turn completions, with per-outcome controls and keyword rules.',
    descriptionZh: '回合完成桌面通知，支持按结果分别控制与关键词规则。',
    tags: ['notification', 'desktop', '通知', '桌面'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-open-in-vscode',
    titleZh: 'VS Code 打开',
    repo: 'https://github.com/omdsh-dev/dsh-open-in-vscode',
    category: 'plugin',
    description: 'Open DSH workspace directories in VS Code directly from the web GUI.',
    descriptionZh: '从 Web GUI 直接用 VS Code 打开 DSH 工作区目录。',
    tags: ['vscode', 'open', 'editor', '编辑器'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-chatnode-wechat',
    titleZh: '微信接入',
    repo: 'https://github.com/Jesse-njx/dsh-chatnode-wechat',
    category: 'plugin',
    description: 'Chat with, monitor, and approve your DSH agents from WeChat via the iLink gateway.',
    descriptionZh: '通过 iLink 网关在微信中与 DSH 代理对话、监控并审批。',
    tags: ['wechat', 'messaging', 'approval', '微信', '消息'],
    author: 'Jesse-njx',
  }),
  entry({
    title: 'deepseek-harness-acp',
    titleZh: 'ACP 接入',
    repo: 'https://github.com/openma-ai/deepseek-harness-acp',
    category: 'plugin',
    description: 'ACP profile plugin and standalone stdio server for using the full DSH agent from Zed and other ACP clients.',
    descriptionZh: 'ACP profile 插件与独立 stdio 服务：可从 Zed 等 ACP 客户端使用完整 DSH 代理。',
    tags: ['acp', 'zed', 'integration', '接入'],
    author: 'openma-ai',
  }),
  entry({
    title: 'telegram',
    titleZh: 'Telegram 桥',
    repo: 'https://github.com/LoserFox/telegram',
    category: 'plugin',
    description: 'Bridge to the Telegram Bot API: long polling, per-chat sessions, HTML formatting.',
    descriptionZh: 'Telegram Bot API 桥：长轮询、按会话隔离、HTML 格式化。',
    tags: ['telegram', 'bot', 'messaging', '消息'],
    author: 'LoserFox',
  }),

  // ── 插件 · 开发与运行时 ───────────────────────────────────────────────
  entry({
    title: 'dsh-boot-guard',
    titleZh: '启动保护',
    repo: 'https://github.com/SaiSenBox/dsh-boot-guard',
    category: 'plugin',
    description: 'Loader-independent startup recovery for DSH Web that detects likely broken plugins, temporarily skips them, and restores.',
    descriptionZh: 'DSH Web 的启动恢复：检测疑似损坏的插件并临时跳过，且只还原其自身修改。',
    tags: ['boot', 'recovery', 'plugin', '启动', '恢复'],
    author: 'SaiSenBox',
  }),
  entry({
    title: 'dsh-testgen',
    titleZh: '测试生成',
    repo: 'https://github.com/bujue600-arch/dsh-testgen',
    category: 'plugin',
    description: 'Automated unit-test generation: a /testgen command and generate_tests tool that scaffold, run, and fix tests until they pass.',
    descriptionZh: '自动单元测试生成：/testgen 命令与 generate_tests 工具会搭建、运行并修复测试直至通过。',
    tags: ['test', 'generation', 'vitest', '测试', '生成'],
    author: 'bujue600-arch',
  }),
  entry({
    title: 'Code2Skill',
    titleZh: '代码转技能',
    repo: 'https://github.com/leechen298/Code2Skill',
    category: 'plugin',
    description: 'Generate Functions, MCP tools, workflow Skills, and offline test packages from user-authorized source code.',
    descriptionZh: '从用户授权的源代码生成函数、MCP 工具、工作流技能与离线测试包。',
    tags: ['skill', 'mcp', 'generation', '技能', '生成'],
    author: 'leechen298',
  }),
  entry({
    title: 'dsh-builtin-toggles',
    titleZh: '内置能力开关',
    repo: 'https://github.com/Starfie1d1272/dsh-builtin-toggles',
    category: 'plugin',
    description: 'Evidence-backed inspector for DSH Web built-in capabilities with fail-closed controls for nine reviewed UI leaves.',
    descriptionZh: '基于证据的 DSH Web 内置能力检查器，并为九个经过审查的 UI 端点提供故障关闭控制。',
    tags: ['inspector', 'toggles', 'diagnostics', '检查', '开关'],
    author: 'Starfie1d1272',
  }),
  entry({
    title: 'dsh-context-doctor',
    titleZh: '上下文审计',
    repo: 'https://github.com/Zhenyu98/dsh-context-doctor',
    category: 'plugin',
    description: 'Context injection audit: token costs of instruction chains / skill catalogs / tool schemas, duplicate and conflict detection.',
    descriptionZh: '上下文注入审计：指令链 / 技能目录 / 工具 schema 的 token 成本，以及重复与冲突检测。',
    tags: ['context', 'audit', 'tokens', '上下文', '审计'],
    author: 'Zhenyu98',
  }),

  // ── 客户端 · UI 增强 ──────────────────────────────────────────────────
  entry({
    title: 'dsh-better-sidebar',
    titleZh: '更好的侧边栏',
    repo: 'https://github.com/omdsh-dev/dsh-better-sidebar',
    category: 'client',
    description: 'Enhanced sidebar for the DSH web UI.',
    descriptionZh: '增强版 DSH Web UI 侧边栏。',
    tags: ['sidebar', 'ui', '侧边栏', '界面'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-ui-whale',
    titleZh: '鲸鱼 UI 皮肤',
    repo: 'https://github.com/omdsh-dev/dsh-ui-whale',
    category: 'client',
    description: 'Whale-themed UI skin collection for the DSH web UI.',
    descriptionZh: 'DSH Web UI 的鲸鱼主题皮肤合集。',
    tags: ['theme', 'skin', 'whale', '主题', '皮肤'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-web-terminal',
    titleZh: 'Web 终端',
    repo: 'https://github.com/omdsh-dev/dsh-web-terminal',
    category: 'client',
    description: 'A web terminal surface for the DSH web UI.',
    descriptionZh: 'DSH Web UI 的 Web 终端面板。',
    tags: ['terminal', 'ui', '终端'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-skills-manager',
    titleZh: '技能管理器',
    repo: 'https://github.com/omdsh-dev/dsh-skills-manager',
    category: 'client',
    description: 'Manage installed skills from the DSH web UI.',
    descriptionZh: '在 DSH Web UI 中管理已安装技能。',
    tags: ['skills', 'manager', 'ui', '技能', '管理'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-at-file',
    titleZh: '@文件引用',
    repo: 'https://github.com/omdsh-dev/dsh-at-file',
    category: 'client',
    description: 'Codex-style @file mentions for DeepSeek Harness: search workspace files in the composer and attach their contents to prompts.',
    descriptionZh: 'Codex 风格 @文件引用：在输入框中搜索工作区文件并附加其内容到提示词。',
    tags: ['file', 'mention', 'composer', '文件', '引用'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-composer-expand',
    titleZh: '输入框展开',
    repo: 'https://github.com/13071301808/dsh-composer-expand',
    category: 'client',
    description: 'Composer expand/collapse toggle: a ⬆/⬇ button grows the input to a tall 70vh writing view.',
    descriptionZh: '输入框展开/收起开关：⬆/⬇ 按钮把输入区扩展到 70vh 高的写作视图。',
    tags: ['composer', 'expand', 'ui', '输入框', '展开'],
    author: '13071301808',
  }),
  entry({
    title: 'dsh-community-hot',
    titleZh: '社区热榜',
    repo: 'https://github.com/littleboylittlegirl/dsh-community-hot',
    category: 'client',
    description: 'Floating community panel: 24h hot topics and hot plugins TOP10 with a draggable, always-on-top button.',
    descriptionZh: '悬浮社区面板：24 小时热门话题与插件 TOP10，可拖拽、置顶。',
    tags: ['hot', 'community', 'panel', '热榜', '社区'],
    author: 'littleboylittlegirl',
  }),
  entry({
    title: 'dsh-plugin-tts',
    titleZh: '语音朗读',
    repo: 'https://github.com/1624318455/dsh-plugin-tts',
    category: 'client',
    description: 'Reads assistant replies aloud via free Edge TTS: per-message buttons, auto-read toggle, voice settings panel.',
    descriptionZh: '通过免费 Edge TTS 朗读助手回复：逐条朗读、自动朗读开关与语音设置面板。',
    tags: ['tts', 'voice', 'read', '朗读', '语音'],
    author: '1624318455',
  }),
  entry({
    title: 'dsh-usage-stats',
    titleZh: '用量统计热力图',
    repo: 'https://github.com/Make0209/dsh-usage-stats',
    category: 'client',
    description: 'GitHub-style usage heatmap dashboard: per-workspace turn counts and token spend, DeepSeek account balance.',
    descriptionZh: 'GitHub 风格用量热力图：按工作区统计轮次与 token 花费，以及 DeepSeek 余额。',
    tags: ['usage', 'stats', 'heatmap', '用量', '统计'],
    author: 'Make0209',
  }),
  entry({
    title: 'dsh-global-rules',
    titleZh: '全局规则编辑',
    repo: 'https://github.com/badai147/dsh-global-rules',
    category: 'client',
    description: 'Edit the global ~/.dsh/AGENTS.md rules from the web settings panel, live on save.',
    descriptionZh: '在 Web 设置面板中编辑全局 ~/.dsh/AGENTS.md 规则，保存即生效。',
    tags: ['rules', 'settings', 'edit', '规则', '设置'],
    author: 'badai147',
  }),
  entry({
    title: 'dsh-web-mobile',
    titleZh: '移动端适配',
    repo: 'https://github.com/mexiaosqwq/dsh-web-mobile',
    category: 'client',
    description: 'Mobile-adaptive layout: the sidebar becomes an overlay drawer, conversation gets the full width.',
    descriptionZh: '移动端自适应布局：侧边栏变为覆盖式抽屉，会话区占满宽度。',
    tags: ['mobile', 'responsive', '移动端', '适配'],
    author: 'mexiaosqwq',
  }),
  entry({
    title: 'dsh-find-plugin',
    titleZh: '让代理帮你找插件',
    repo: 'https://github.com/awesome-dsh-plugin/dsh-find-plugin',
    category: 'client',
    description: 'Lets your agent find plugins for you (dsh plugin --profile web add dsh-find-plugin).',
    descriptionZh: '让代理帮你寻找插件（dsh plugin --profile web add dsh-find-plugin）。',
    tags: ['find', 'search', '找插件'],
    author: 'awesome-dsh-plugin',
    npm: 'dsh-find-plugin',
  }),

  // ── 客户端 · 主题外观 ─────────────────────────────────────────────────
  entry({
    title: 'dsh-dream-skin',
    titleZh: '梦境皮肤',
    repo: 'https://github.com/RevolutionLA/dsh-dream-skin',
    category: 'client',
    description: 'One-command skin plugin: 8 original themes, translucent wallpaper, per-user accent, shareable theme-pack import/export.',
    descriptionZh: '一键皮肤插件：8 套原创主题、半透明壁纸、个性化强调色、主题包导入导出。',
    tags: ['theme', 'skin', 'wallpaper', '主题', '皮肤', '壁纸'],
    author: 'RevolutionLA',
  }),
  entry({
    title: 'dsh-skin',
    titleZh: 'Codex 风格皮肤',
    repo: 'https://github.com/KinGao294/dsh-skin',
    category: 'client',
    description: 'Codex-style skin switcher plus a custom wallpaper layer with opacity and blur controls.',
    descriptionZh: 'Codex 风格皮肤切换器，外加不透明度与模糊控制的壁纸层。',
    tags: ['theme', 'skin', 'codex', '主题', '皮肤'],
    author: 'KinGao294',
  }),
  entry({
    title: 'dsh-font',
    titleZh: '字体切换',
    repo: 'https://github.com/tianyhjg-lab/dsh-font',
    category: 'client',
    description: 'Font switcher: 99 UI fonts and 31 code fonts with CJK-Latin pairing stacks, instant apply and localStorage persistence.',
    descriptionZh: '字体切换器：99 款 UI 字体与 31 款代码字体，含中日韩-拉丁配对，即时生效并本地持久化。',
    tags: ['font', 'theme', '字体', '主题'],
    author: 'tianyhjg-lab',
  }),
  entry({
    title: 'dsh-deep-whale',
    titleZh: '深海鲸娘皮肤',
    repo: 'https://github.com/Small-tailqwq/dsh-deep-whale',
    category: 'client',
    description: 'Whale-girl skin series for the DSH Web UI (maid-atelier).',
    descriptionZh: 'DSH Web UI 鲸娘皮肤系列（maid-atelier）。',
    tags: ['theme', 'skin', 'whale', '主题', '皮肤'],
    author: 'Small-tailqwq',
  }),

  // ── Skill ─────────────────────────────────────────────────────────────
  entry({
    title: 'dsh-plugin-dev',
    titleZh: 'DSH 插件开发档案',
    repo: 'https://github.com/omdsh-dev/dsh-plugin-dev',
    category: 'skill',
    description: 'DeepSeek Harness plugin-development experience archive: form selection, defineTool, bundle mounting, testing, publishing.',
    descriptionZh: 'DSH 插件开发踩坑与做法档案：形态选择、defineTool、bundle 挂载、测试与发布。',
    tags: ['skill', 'plugin-dev', 'development', '技能', '插件开发'],
    author: 'omdsh-dev',
  }),
  entry({
    title: 'dsh-reverse-skill',
    titleZh: '逆向工程技能包',
    repo: 'https://github.com/dhicoc/dsh-reverse-skill',
    category: 'skill',
    description: 'Complete reverse-skill pack (85 SKILL.md) as a Cordis plugin: reverse engineering, authorized pentesting and security research.',
    descriptionZh: '完整逆向技能包（85 个 SKILL.md）：逆向工程、授权渗透测试与安全研究。',
    tags: ['skill', 'reverse', 'security', '技能', '逆向', '安全'],
    author: 'dhicoc',
  }),
  entry({
    title: 'dsh-design-skills',
    titleZh: '设计美学技能包',
    repo: 'https://github.com/zhaiyateng/dsh-design-skills',
    category: 'skill',
    description: 'Design-aesthetics skill pack (10 styles) with runnable landing-page demos: tokens, component rules, forbidden lists, acceptance checklists.',
    descriptionZh: '设计美学技能包（10 种风格）带可运行落地页示例：token、组件规则、禁用清单与验收清单。',
    tags: ['skill', 'design', 'ui', '技能', '设计'],
    author: 'zhaiyateng',
  }),
  entry({
    title: 'dsh-skill-pack',
    titleZh: '可分享工作流技能包',
    repo: 'https://github.com/jeremy9682/dsh-skill-pack',
    category: 'skill',
    description: '11 shareable workflow skills (handoff, triage, to-spec, to-tickets, wayfinder, teach, wait-what, …) as an installable skill pack.',
    descriptionZh: '11 个可分享的工作流技能（交接、分诊、按规格、转工单、探路、教学等）作为可安装技能包。',
    tags: ['skill', 'workflow', 'pack', '技能', '工作流'],
    author: 'jeremy9682',
  }),
  entry({
    title: 'hermes-dsh-collab',
    titleZh: 'Hermes 流水线协作',
    repo: 'https://github.com/Cavan-Ou/hermes-dsh-collab',
    category: 'skill',
    description: 'Hook DeepSeek Harness into a Hermes pipeline: dispatch-spec template, model-tier routing, orchestrator quality gates, as a SKILL.md pack.',
    descriptionZh: '把 DSH 接入 Hermes 流水线：派发规范模板、模型分级路由、编排质量门，以 SKILL.md 包发布。',
    tags: ['skill', 'hermes', 'pipeline', '技能', '流水线'],
    author: 'Cavan-Ou',
  }),

  // ── 开发资源 ──────────────────────────────────────────────────────────
  entry({
    title: 'awesome-dsh-plugin',
    titleZh: 'DSH 插件精选列表',
    repo: 'https://github.com/awesome-dsh-plugin/awesome-dsh-plugin',
    category: 'dev-resource',
    description: 'A curated list of plugins for DeepSeek Harness (dsh). 500+ installable community plugins across 12 categories.',
    descriptionZh: 'DeepSeek Harness 插件精选列表：12 个分类共 500+ 可安装社区插件。',
    tags: ['awesome', 'list', 'index', '精选', '列表', '索引'],
    author: 'awesome-dsh-plugin',
  }),
  entry({
    title: 'dsh-market',
    titleZh: 'dsh-market 插件市场',
    repo: 'https://github.com/dsh-market/dsh-market',
    category: 'dev-resource',
    description: 'The plugin market inside DeepSeek Harness (Settings page): browse/search the community catalog, one-click install and update, themes.',
    descriptionZh: 'DSH 内置插件市场（设置页）：浏览/搜索社区目录、一键安装与更新、主题管理。',
    tags: ['market', 'store', 'plugins', '市场', '商店'],
    author: 'dsh-market',
    npm: 'dshmarket',
  }),
  entry({
    title: 'dsh-store',
    titleZh: 'dsh-store 插件商店',
    repo: 'https://github.com/huguangyu666/dsh-store',
    category: 'dev-resource',
    description: 'Plugin store: npm authoritative catalog + awesome curated list (550+ plugins, 11 categories), official dsh plugin add/remove one-click install, sidebar + settings entry.',
    descriptionZh: '插件商店：npm 权威目录 + awesome 精选列表（550+ 插件、11 分类），官方 dsh plugin add/remove 一键安装，侧边栏 + 设置双入口。',
    tags: ['market', 'store', 'plugins', '市场', '商店'],
    author: 'huguangyu666',
  }),
  entry({
    title: 'dsh-plugin-manager',
    titleZh: 'dsh pm 插件管理器',
    repo: 'https://github.com/Jesse-njx/dsh-plugin-manager',
    category: 'dev-resource',
    description: 'The dsh pm plugin manager: multi-source search (awesome list + GitHub + npm), install/remove/update per profile, doctor audit.',
    descriptionZh: 'dsh pm 插件管理器：多源搜索（awesome + GitHub + npm）、按 profile 安装/移除/更新、doctor 审计。',
    tags: ['market', 'manager', 'pm', '管理', '审计'],
    author: 'Jesse-njx',
  }),
  entry({
    title: 'dsh-workshop',
    titleZh: '工坊式插件商店',
    repo: 'https://github.com/loguhan/dsh-workshop',
    category: 'dev-resource',
    description: 'Steam Workshop-style plugin store: browse, search, one-click install with mirror acceleration, progress UI, security checks, Chinese descriptions.',
    descriptionZh: 'Steam 工坊式插件商店：浏览、搜索、一键安装（镜像加速、进度 UI、安全检查、中文描述）。',
    tags: ['market', 'workshop', 'store', '商店', '工坊'],
    author: 'loguhan',
  }),
  entry({
    title: 'dsh-plugin-workshop',
    titleZh: '插件工坊',
    repo: 'https://github.com/yyyyukari/dsh-plugin-workshop',
    category: 'dev-resource',
    description: 'Steam Workshop-style in-app plugin browser: hot/newest/trending sorting, Chinese keyword mapping, bilingual descriptions, one-click install/update.',
    descriptionZh: 'Steam 工坊式应用内插件浏览器：热门/最新/趋势排序、中文关键词映射、双语描述、一键安装/更新。',
    tags: ['market', 'workshop', 'browser', '工坊', '浏览'],
    author: 'yyyyukari',
  }),
  entry({
    title: 'deepseek-harness',
    titleZh: 'DeepSeek Harness 官方仓库',
    repo: 'https://github.com/deepseek-ai/deepseek-harness',
    category: 'dev-resource',
    description: 'Official DeepSeek Harness repository: the plugin-based agent harness this panel runs inside.',
    descriptionZh: 'DeepSeek Harness 官方仓库：本面板所运行的插件化代理框架。',
    tags: ['official', 'harness', 'docs', '官方', '框架'],
    author: 'deepseek-ai',
  }),
];

/** Map repo URL → seed entry, used to merge curated zh translations over live fetch results. */
export const SEED_BY_REPO = new Map<string, CatalogEntry>();
for (const seed of SEED_ENTRIES) {
  if (seed.repo) {
    const base = seed.repo.split('#')[0];
    if (!SEED_BY_REPO.has(base)) SEED_BY_REPO.set(base, seed);
  }
}
